[package]
name = "softnet"
version = "0.1.0"
publish = false
edition = "2021"

[lib]
path = "lib/mod.rs"

[dependencies]
smoltcp = "0.8.1"
libc = "0.2.126"
polling = "2.2.0"
dhcproto = "0.7.0"
vmnet = "0.1.1"
clap = { version = "3.1.18", features = ["derive"] }
mac_address = "1.1.3"
privdrop = "0.5.2"
thiserror = "1.0.31"
ip_network = "0.4.1"
users = "0.11.0"
system-configuration = "0.5.0"
num_enum = "0.5.7"
